### ISSUE TITLE
Create a sample using React and rest-api-node

### ISSUE THREAD

**Issue by renanlopescoder** [renanlopescoder/rest-api-node#1]
Create a simple front-end using the api and add to README.md in Showcases

**Comment by niradler** [comment]
hi, im interesting any guidance of what kind of example ?

**Comment by renanlopescoder** [comment]
Hi, you can use React and Redux or MobX and mobx-state-tree,
We have this sample using Angular 4: https://github.com/renanlopescoder/typescript-angular4

Useful links:
mobx-state-tree: https://github.com/mobxjs/mobx-state-tree 
mobx: https://github.com/mobxjs/mobx
mobx-react: https://github.com/mobxjs/mobx-react
Content about mobx and react: https://www.youtube.com/watch?v=Dp75-DnGFrU&t=314s

**Comment by renanlopescoder** [comment]
@niradler if you want to create this interface with react and mobx-state-tree let me know, i can help you in this open source project

**Comment by niradler** [comment]
sure im in, i will read the links you provide, and build a skeleton project.

**Comment by niradler** [comment]
amm i forgot to push the project but i manage to do simple example like the angular 4 example 
https://github.com/niradler/react-rest-api-node i will push it on sunday and then let me know if you have any suggestion im new to react mobx

**Comment by niradler** [comment]
@renanlopescoder did u had the chance to look ?

**Comment by renanlopescoder** [comment]
@niradler good project, please provide me your e-mail and demo link to update the readme.md and add your project in showcases section,

**Comment by niradler** [comment]
@renanlopescoder 
Name: Nir Adler
Email: niradler55@gmail.com
demo link : https://niradler.github.io/react-rest-api-node/
