### ISSUE TITLE
Hacktoberfest/add_email_service_create_user

### ISSUE THREAD

**Issue by renanlopescoder** [renanlopescoder/rest-api-node#12]
Add mail service with gmail and nodemailer

**Comment by FlopiVG** [comment]
Hi, can u give more details?

**Comment by renanlopescoder** [comment]
I am doing this task, using nodemailer =)

**Comment by FlopiVG** [comment]
Ok, i will check it :)

Edit: u want only send an email or send a confirm email?

**Comment by renanlopescoder** [comment]
@FlopiVG you can do this issue =) https://github.com/renanlopescoder/rest-api-node/issues/13

**Comment by renanlopescoder** [comment]
Done =)
