### ISSUE TITLE
Hacktoberfest/chenge-database-mlab-to-firebase

### ISSUE THREAD

**Issue by renanlopescoder** [renanlopescoder/rest-api-node#13]
Update the readme.md with firebase info

email: rest-api-node@gmail.com
password: hacktoberfestpassword

**Comment by FlopiVG** [comment]
You mean just change the readme.md?

**Comment by renanlopescoder** [comment]
Change the database service too

**Comment by FlopiVG** [comment]
Ok =)

**Comment by FlopiVG** [comment]
You  mean implement this? https://www.npmjs.com/package/firebase

Srry is my first time implementing firebase.

**Comment by renanlopescoder** [comment]
You can use this https://firebase.google.com/docs/web/setup

**Comment by renanlopescoder** [comment]
Let me know if you get any issue =)

**Comment by FlopiVG** [comment]
I create a firebase account and connect for database, i think i will to refactor all services to connect into firebase api.

I dont find any type of schema types in firebase like mongoose.

**Comment by renanlopescoder** [comment]
The project need some changes to use firebase, =) https://firebase.google.com/support/guides/firebase-web?hl=pt-br
