### ISSUE TITLE
Create a sample using vue.js and rest-api-node

### ISSUE THREAD

**Issue by renanlopescoder** [renanlopescoder/rest-api-node#2]
Create a simple front-end using the api and add to README.md in Showcases

**Comment by smkamranqadri** [comment]
I am working on it.

**Comment by renanlopescoder** [comment]
Please when you finish that project, please provide me your demo link, repository link, your name and email.

**Comment by smkamranqadri** [comment]
Sure

**Comment by renanlopescoder** [comment]
Done:
http://vue-clash.herokuapp.com/
https://github.com/renanlopescoder/vue
